name: phpunit

on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.0", "8.1", "8.2" ]
                laravel: [ "8.0", "9.0", "10.0" ]
                dragon: [ "5.8", "6.0" ]
                exclude:
                    -   laravel: "10.0"
                        php: "8.0"

        name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: composer require --dev laravel/framework:^${{ matrix.laravel }} dragon-code/support:^${{ matrix.dragon }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
